name: native-image-compile

on: [push]

jobs:
  native-image-compile-in-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login into Heroku Container Registry first, so that we can push our Image later
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin registry.heroku.com

      - name: Compile Native Image using Docker
        run: docker build . --tag=registry.heroku.com/spring-boot-graal/web

      - name: Push to Heroku Container Registry
        run: docker push registry.heroku.com/spring-boot-graal/web

      - name: Release Dockerized Native Spring Boot App on Heroku
        run: ./heroku-release.sh spring-boot-graal

