# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: antanalyzer

on:
  workflow_dispatch: null

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: adopt
      - name: Build with Maven
        run: |
          echo $DISPLAY
          echo "hallo"
          unset DISPLAY
          echo $DISPLAY
          mvn clean package -DskipTests --batch-mode --update-snapshots package
      - name: Upload test result
        uses: actions/upload-artifact@v2
        with:
          name: zip release
          path: target/antanalyzer*.zip